# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-20 18:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='景点名称')),
                ('desc', models.CharField(max_length=300, verbose_name='景点介绍')),
                ('banner', models.ImageField(upload_to='theme/spot/%Y/%m', verbose_name='景点大图')),
                ('cost', models.IntegerField(default=0, verbose_name='门票价格')),
                ('image1', models.ImageField(upload_to='theme/spot/%Y/%m', verbose_name='景点小图1')),
                ('image2', models.ImageField(upload_to='theme/spot/%Y/%m', verbose_name='景点小图2')),
                ('summary1', models.CharField(max_length=300, verbose_name='景点介绍1')),
                ('summary2', models.CharField(max_length=300, verbose_name='景点介绍2')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '景点',
                'verbose_name_plural': '景点',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='主题名称')),
                ('desc', models.CharField(max_length=300, verbose_name='主题介绍')),
                ('image', models.ImageField(upload_to='theme/%Y/%m', verbose_name='主题图片')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '主题',
                'verbose_name_plural': '主题',
            },
        ),
        migrations.AddField(
            model_name='spot',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.Theme', verbose_name='主题'),
        ),
    ]
