# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-23 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_auto_20180223_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='banner',
            field=models.ImageField(blank=True, upload_to='theme/spot/%Y/%m', verbose_name='景点大图'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='image1',
            field=models.ImageField(blank=True, upload_to='theme/spot/%Y/%m', verbose_name='景点小图1'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='image2',
            field=models.ImageField(blank=True, upload_to='theme/spot/%Y/%m', verbose_name='景点小图2'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='image',
            field=models.ImageField(blank=True, upload_to='theme/%Y/%m', verbose_name='主题图片'),
        ),
    ]
