# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-23 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='users/default.png', upload_to='users/%Y/%m', verbose_name='头像'),
        ),
    ]
