# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-23 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180223_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='users/default.png', upload_to='users/%Y/%m', verbose_name='头像'),
        ),
    ]
